# Generated by Django 6.0.1 on 2026-02-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='join_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='start_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
